# HA mode with autoscaling

namespaceOverride: "argo"

redis-ha:
  enabled: false # Due to local 1 node cluster

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2